yolo_model:

  config_file:
    name: yolov3-tiny_3l-mbzirc_anchors.cfg
  weight_file:
    name: yolov3-tiny_3l-mbzirc_anchors_4000.weights
  threshold:
    value: 0.4
  nsm_threshold:
    value: 0.2
  detection_classes:
    names:
      - drone
      - ball
