# MBZIRC detector: ROS configuration of supported cameras
# Useful links:
#   https://en.wikipedia.org/wiki/Image_sensor_format
#   https://www.vision-doctor.com/en/camera-technology-basics/sensor-and-pixel-sizes.html

cameras:

    ###############################################
    # Camera-specific configuration               #
    # Change only to add support for a new camera #
    ###############################################

    ausdom:
        fullname: Ausdom_Webcam
        topic: /ausdom/image_raw
        stereo: false

    mobius:
        fullname: Mobius_ActionCam
        topic: /mobius/image_raw
        stereo: false

    runcam2:
        fullname: RunCam2_ActionCam
        topic: /runcam2/image_raw
        stereo: false

    zed:
        fullname: Zed_StereoCam
        topic: /zed/image_raw
        stereo: true
