# MBZIRC detector configuration of ROS parameters

subscribers:

    input_camera:
        topic: /mux_cam/image_raw


cameras:

  long_dist:
    name: Mobius_ActionCam
    topic: /mobius_cam/image_raw
    stereo: false

  short_dist:
    name: Ausdom_Webcam
    topic: /ausdom_cam/image_raw
    stereo: false

#   name: Zed_StereoCam
#   topic: /zed_cam/image_raw
#   stereo: true

